name: Continuous Deployment

on:
  push:
    branches:
      - submission-2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and deploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            ls
            cd ~/backend-expert-learning/auth-api
            ls
            git pull origin master
            yarn install
            yarn migrate up
            pm2 restart auth-api
